services:
  api:
    build:
      context: .
    container_name: api
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env.${NODE_ENV}
    environment:
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - mongo # Ensures MongoDB starts before the API
    restart: always # Automatically restart the API container on failure

  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017" # Exposes MongoDB default port
    volumes:
      - mongo-data:/data/db # Persists MongoDB data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root # MongoDB root username
      - MONGO_INITDB_ROOT_PASSWORD=root4312 # MongoDB root password
    restart: always # Automatically restart the MongoDB container on failure

volumes:
  mongo-data:
